export type { MigrationResult } from './types'
export { migrateServerConfig, CURRENT_SERVER_CONFIG_VERSION } from './server/config'
export { migrateServerRegistersState, CURRENT_SERVER_ZUSTAND_VERSION } from './server/zustand'
export { migrateClientConfig, CURRENT_CLIENT_CONFIG_VERSION } from './client/config'
export { migrateRootState, CURRENT_ROOT_ZUSTAND_VERSION } from './client/zustand'
